In [1]:
import numpy as np
import pandas as pd
import seaborn as sb
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("train.txt", sep=';', header=None, names=['text', 'emotion'])
# ye text file me data hai to 
# sep=';' is used to specify that the data is separated by a semicolon
# header=None is used to indicate that there is no header row in the data
# names=['text', 'emotion'] is used to assign column names to the data
# text column me text data hai aur emotion column me emotion data hai
# df is a dataframe that contains the data from the text file
# df.head() is used to display the first 5 rows of the dataframe

In [3]:
df.head()

                                                text  emotion
0                            i didnt feel humiliated  sadness
1  i can go from feeling so hopeless to so damned...  sadness
2   im grabbing a minute to post i feel greedy wrong    anger
3  i am ever feeling nostalgic about the fireplac...     love
4                               i am feeling grouchy    anger

In [4]:
df.isnull().sum()

text       0
emotion    0
dtype: int64

In [5]:
df['emotion'].value_counts()

emotion
joy         5362
sadness     4666
anger       2159
fear        1937
love        1304
surprise     572
Name: count, dtype: int64

In [6]:
unique_emotions = df['emotion'].unique()\
    # ye unique_emotions variable me unique emotions store kar raha hai jo emotion column me hai
emotion_numbers = {}
i = 0
for emo in unique_emotions:
    # ye sab me numbea ko add karega incerement ke sath
    emotion_numbers[emo] = i
    i += 1
    
    df['emotion'] = df['emotion'].map(emotion_numbers)

In [7]:
df

                                                    text  emotion
0                                i didnt feel humiliated      NaN
1      i can go from feeling so hopeless to so damned...      NaN
2       im grabbing a minute to post i feel greedy wrong      NaN
3      i am ever feeling nostalgic about the fireplac...      NaN
4                                   i am feeling grouchy      NaN
...                                                  ...      ...
15995  i just had a very brief time in the beanbag an...      NaN
15996  i am now turning and i feel pathetic that i am...      NaN
15997                     i feel strong and good overall      NaN
15998  i feel like this was such a rude comment and i...      NaN
15999  i know a lot but i feel so stupid because i ca...      NaN

[16000 rows x 2 columns]

In [8]:
df['text'] = df['text'].apply(lambda x: x.lower())
# ye text column me jo text hai usko lowercase me convert kar raha hai
# lambda function is used to apply the function to each element of the text column
# x is the input to the lambda function and x.lower() is the output of the lambda function
# df['text'] is the text column of the dataframe and .apply() is used

In [9]:
import string
def remove_Punc(text):
    return text.translate(str.maketrans('', '', string.punctuation))
# ye remove_Punc function me text ko input le raha hai aur usme se punctuation ko remove kar raha hai
# string.punctuation is a string that contains all the punctuation characters
# str.maketrans() is a method that creates a translation table that can be used to replace or remove characters
# in this case we are replacing punctuation characters with an empty string
# so that they are removed from the text
# the output of this function is the text without punctuation characters

In [10]:
df['text'] = df['text'].apply(remove_Punc)

In [11]:
def remove_numbers(text):
    new = ""
    for i in text:
        if not i.isdigit():
            new = new + i
    return new
df['text'] = df['text'].apply(remove_numbers)
# remove the numbers from the text column

In [12]:
# remove the URLs $ Links from the text column emoji etc
def remove_emojis(txt):
    new = ""
    for i in txt:
        if i.isascii():
            new +=i
    return new

df['text'] = df['text'].apply(remove_emojis)
# ye remove_emojis function me txt ko input le raha hai aur usme se emojis ko remove kar raha hai
# isascii() method is used to check if the character is an ASCII character or not
# if the character is an ASCII character then it is added to the new string
# if the character is not an ASCII character then it is not added to the new string
# the output of this function is the text without emojis

In [13]:
# remove the stop words from the text column

import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
nltk.download('stopwords')
nltk.download('punkt')
stop_words = set(stopwords.words('english'))
def remove_stopwords(text):
    new = ""
    for i in text.split():
        if i not in stop_words:
            new = new + " " + i
    return new
df['text'] = df['text'].apply(remove_stopwords)
# ye remove_stopwords function me text ko input le raha hai aur usme se stop words ko remove kar raha hai
# stop words are the common words that do not add much meaning to the text such as is, the, a, an etc
# stop_words is a set that contains all the stop words
# text.split() is used to split the text into words and then we are checking if each word is in the stop_words set or not
# if the word is not in the stop_words set then it is added to the new string
# the output of this function is the text without stop words

[nltk_data] Downloading package stopwords to
[nltk_data]     /home/raushan/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to /home/raushan/nltk_data...
[nltk_data]   Package punkt is already up-to-date!

In [14]:
stop_words = set(stopwords.words('english'))
len(stop_words)

198

In [15]:
df.loc[1]['text']

' go feeling hopeless damned hopeful around someone cares awake'

In [16]:
def remove(txt):
  words = txt.split()
  cleaned = []
  for i in words:
    if i not in stop_words:
      cleaned.append(i)
  return ' '.join(cleaned)
# ye remove function me text ko input le raha hai aur usme se stop words ko remove kar raha hai
# stop words are the common words that do not add much meaning to the text such as is 
# the, a, an etc
# stop_words is a set that contains all the stop words
# text.split() is used to split the text into words and then we are checking if each word is in the stop_words set or not
# if the word is not in the stop_words set then it is added to the cleaned list
# the output of this function is the text without stop words

df['text'] = df['text'].apply(remove)

In [17]:
df['text'] = df['text'].apply(remove)

In [18]:
df.loc[1]['text']

'go feeling hopeless damned hopeful around someone cares awake'

In [ ]:
from sklearn.model_selection import train_test_split

train_test, X_test, y_test = train_test_split(X, y, test_size=0.2, random_state=42)